cc_binary(
    name = "static_btree_benchmark",
    srcs = ["static_btree_benchmark.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "@google_benchmark//:benchmark_main",
    ],
)
